### ISSUE TITLE
Bungeecord Support

### ISSUE THREAD

**Issue by doitliketyler** [jflory7/PlayerLink#8]
I have 5 servers so It would be nice to have Bungeecord support so I could configure it once globally versus on all of my spigot servers.

**Comment by jflory7** [comment]
@doitliketyler: What exactly do you mean for BungeeCord support? Do you just mean to make it run on all of the servers globally versus setting it up on each individual server?

**Comment by doitliketyler** [comment]
Yes, thats exactly it

**Comment by jflory7** [comment]
I'm assigning this issue as `wontfix`. The request would consist of this being an entirely new plugin written in the BungeeCord API. While it may be something I try pursuing in the future, for now, it is out of the scope of this plugin.

Hopefully I'll have some time to dig into the BungeeCord API soon.
